# Generated by Django 4.2.5 on 2023-09-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='year',
        ),
    ]
